run::
	perl MLbatchSetup.pl
	chmod u+x *JobList.txt
	./setupJobList.txt
	./trainingJobList.txt
	./validationJobList.txt
	./wrapupJobList.txt

clean::
	rm -rf data models *JobList.txt *.ra trans_predictions
